spring:
  datasource:
     driver-class-name: com.mysql.jdbc.Driver
     username: root
     password: 123456
     url: jdbc:mysql://192.168.1.107/sell?characterEncoding=utf-8&useSSL=false
  jpa:
    show-sql: true
  jackson:
    default-property-inclusion: non_null
server:
  servlet:
    context-path: /sell
wechat:
    mpAppId: wx0f798925d06b9e83
    mpAppSecret: d4706ec4638eb04f92033e3f5a13d8f4
    openAppId: wx6ad144e54af67d87
    openAppSecret: 91a2ff6d38a2bbccfb7e9f9079108e2e
    mchId: 1483469312
    mchKey: 06C56A89949D617xxxxxxxxxxx
    keyPath: /var/weixin_cert/h5.p12
    notifyUrl: http://srsell.natapp1.cc/sell/pay/notify

